### ISSUE TITLE
Cargo zng res does not search for metadata in cdylib (Android) crates

### ISSUE THREAD

**Issue by SamRodri** [SamRodri/zng#489]
#### I tried this code:

```toml
[package]
name = "miscomp-issue-mobile"
version = "0.1.0"
edition = "2021"
license = "TODO"
[package.metadata.zng.about]
app = "miscomp-issue"
org = "Zng Project"
qualifier = "rs.zng"

[lib]
# required by Android
crate-type = ["cdylib"]
```

#### Following these steps:

1 - Call `cargo zng res --metadata-dump`

#### I saw this happen:

No metadata found, because it only searches in `bin` crates.

#### I expected this to happen:

Use metadata from `lib` crates. (maybe only if it has `zng.about` metadata.
